### ISSUE TITLE
pybel can not work on python3.7

### ISSUE THREAD

**Issue by pastroal1979** [pybel/pybel#394]
I installed the pybel on python3.7 by pip, tried python 32bit and 64bit both. The result is the same.
Error:AttributeError: module 'pybel' has no attribute 'readstring'
How to install pybel correctly?

![image](https://user-images.githubusercontent.com/5545742/66256422-3c205600-e7c0-11e9-983f-d1b96c006cbe.png)
![image](https://user-images.githubusercontent.com/5545742/66256469-b5b84400-e7c0-11e9-913b-a48124e9db5e.png)

**Comment by cthoyt** [comment]
Hi, rhis repository is related to the Biological Expression Langauge (BEL), and you're probably looking for the OpenBabel documentation at https://github.com/openbabel/openbabel documentation or https://github.com/openbabel/openbabel/tree/master/scripts/python
